version: '3.8'

services:
  glance:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./glance.yml:/app/glance.yml
    restart: unless-stopped